### ISSUE TITLE
v1 todo

### ISSUE THREAD

**Issue by joneff** [telerik/mvc-tripxpert-pwa#1]
* [x] Remove extra dependencies
* [x] Reduce the images to say 20 per tour
* [x] Create image handler to handle different resolutions of images
* [x] Test custom kendo build from package
* [x] Image folder structure is changed; update references for images

For anything, you can ask me
